---
argument_specs:
  main:
    short_description: "Deploy SPB fabric on VOSS switches"
    options:
      extreme_fabric_setup_host:
        description: Target host address
        type: str
        required: true
      extreme_fabric_setup_username:
        description: Authentication username
        type: str
      extreme_fabric_setup_password:
        description: Authentication password
        type: str
      extreme_fabric_setup_api_key:
        description: API key for authentication
        type: str
      extreme_fabric_setup_validate_certs:
        description: Validate SSL certificates
        type: bool
        default: true
      extreme_fabric_setup_state:
        description: Desired state
        type: str
        default: present
        choices: [present, absent]
